name: talker_client
description: A Dart client library for the Talker Server, supporting authentication and real-time chat.
version: 1.0.0
environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.6.0
  web_socket_channel: ^2.4.0
  json_annotation: ^4.9.0
  retrofit: ">=4.0.0 <4.9.0"
  freezed_annotation: ^3.1.0

dev_dependencies:
  test: ^1.24.0
  mocktail: ^1.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  lints: ^2.1.1
  freezed: ^3.1.0
  retrofit_generator: ^9.0.0
